### ISSUE TITLE
Unable to deploy code for pre-requisites

### ISSUE THREAD

**Issue by jroh-aa** [Azure/azure-kusto-microhack#12]
I was working on the deployment and got stuck on step 4:
```
PS /home/azureuser/ADX-IoT-Analytics-Solution-Accelerator> . ./deploy.sh
ResourceUnavailable: Program 'deploy.sh' failed to run: An error occurred trying to start process '/home/azureuser/ADX-IoT-Analytics-Solution-Accelerator/deploy.sh' with working directory '/home/azureuser/ADX-IoT-Analytics-Solution-Accelerator'. No such file or directoryAt line:1 char:1
+ . ./deploy.sh
+ ~~~~~~~~~~~~~.

```

**Comment by guregini** [comment]
Hi @jroh-aa,  are you sure you logged in to the Azure Cross-platform Command Line Interface?
After step 1, you must log in using the prompted URL, even if you're already logged in to Azure portal. 

This is the expected output of az login:
_guy@Azure:~/ADX-IoT-Analytics-Solution-Accelerator$ az login
Cloud Shell is automatically authenticated under the initial account signed-in with. Run 'az login' only if you need to use a different account
**To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code <XXXX> to authenticate**_

In addition, after step 3 (git clone), could you please run "ls" (to ensure the repository has been cloned with its content)? 
This is the expected output:
![image](https://user-images.githubusercontent.com/45633598/189961852-c62d9023-701b-410e-9b0c-baef3dc5b582.png)

Please let me know if that helps

**Comment by guregini** [comment]
We haven't gotten any updates. Closing this PR for now. Let us know if you still need help!
