### ISSUE TITLE
Badge verification link is not provided any more, after course completion.

### ISSUE THREAD

**Issue by ltolstoy** [Azure/azure-kusto-microhack#24]
Hi, I've completed "Azure Data Explorer Microhack" course at 4/9/2024, and also filled and submitted all 3 Answer sheets for Microhack 1, 2,3.
Today is 4/25/2024, and I still did not receive any info or communication related to course completion or badge (verification link, link to credly.com page, etc), so I can't put it to my profile.
Who I need to contact to fix this issue?

**Comment by hfleitas** [comment]
+ @SuryaTejaJosyula , @guregini

**Comment by ltolstoy** [comment]
Hello, today is a 5/6/2024, and I had not received any information or communication related to course completion or badge (verification link, link to credly.com page, etc) yet. Please let me know if you need any additional information.

**Comment by SuryaTejJosyula** [comment]
@ltolstoy Thank you for your patience. Please check your gmail leontol@gmail.com and confirm if you have received your badge.
